//! Every sample must open and draw something. A sample that does not load is
//! the worst possible first thing for somebody to try.

use easel::Board;
use plotkit::{Canvas, Cx, View};

#[test]
fn every_sample_opens_and_draws() {
    let dir = std::path::Path::new("../samples");
    if !dir.exists() {
        // Generated by `cargo run -p studio --bin sample`, so a checkout that
        // has not run it yet is not a failure.
        println!("no samples/ yet -- run `cargo run -p studio --bin sample`");
        return;
    }
    let mut seen = 0;
    for entry in std::fs::read_dir(dir).expect("read samples") {
        let path = entry.expect("an entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("easel") {
            continue;
        }
        seen += 1;
        let name = path.display().to_string();
        let mut b = Board::new();
        let confused = b.load(&name).unwrap_or_else(|e| panic!("{name} would not open: {e}"));
        assert_eq!(confused, 0, "{name} had {confused} lines it could not read");
        assert!(!b.sheet.is_empty() || !b.sheet.script.is_empty(), "{name} is empty");

        // And it must put ink on a canvas, at rest and while playing.
        for t in [0.0, 0.9, 1.8] {
            b.clock = t;
            let mut c = Canvas::new(400, 300);
            c.clear(0);
            b.frame().draw(&mut c, &View::centred(400, 300, 26.0));
            let lit = c.buf.iter().filter(|p| **p != 0).count();
            assert!(lit > 50, "{name} drew almost nothing at t={t} ({lit} pixels)");
        }
        assert!(b.written().errors.is_empty(), "{name} has a script error: {:?}", b.written().errors);
        let _ = Cx::ZERO;
    }
    assert!(seen >= 3, "expected the samples to be there, found {seen}");
}
